version: '3.8'

services:
  app:
    image: ghcr.io/christianf7/elcontact:main
    environment:
      - API_KEY=${API_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - ./contacts.json:/usr/src/app/contacts.json
    networks:
      - app_network

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    depends_on:
      - app
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge