declare module 'express';
declare module 'multer';
declare module 'csv-parse/sync';
declare module 'nedb-promises';
declare module 'node-fetch';
declare module 'dotenv';
declare module 'fs';
declare module 'path';
declare module 'crypto';
declare module 'http';
declare module 'url';
declare module 'events';
declare var process: any;
declare var __dirname: string;
declare type Buffer = any;
